#include "edgetpu/cpp/tools/tflite_graph_util.h"

#include "absl/strings/str_cat.h"
#include "gflags/gflags.h"
#include "glog/logging.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"

DEFINE_string(
    test_srcdir,
    "knowledge/cerebra/spacepark/darwinn/git/edgetpu/cpp/tools/testdata",
    "test data src directory");

DEFINE_string(test_tmpdir, "/tmp", "test data output directory");

namespace coral {
namespace tools {
namespace {

std::string TestFilePath(const std::string& filename) {
  return absl::StrCat(FLAGS_test_srcdir, "/", filename);
}

std::string TempFilePath(const std::string& filename) {
  return absl::StrCat(FLAGS_test_tmpdir, "/", filename);
}

// This test compares the results of model concatenation with recorded golden
// results. The test models are real production models.
void TestConcatModels(const std::string& graph0_path,
                      const std::string& graph1_path,
                      const std::string& expected_graph) {
  const std::string result_path = TempFilePath("merged.tflite");
  // Remove output model generated by previous tests.
  std::remove(result_path.c_str());

  ConcatTfliteModels(graph0_path, graph1_path, result_path);

  std::string result_str;
  ReadFileOrDie(result_path, &result_str);

  std::string expected_str;
  ReadFileOrDie(expected_graph, &expected_str);

  EXPECT_EQ(expected_str, result_str) << result_path;
}

TEST(TfliteGraphUtilTest, ConcatMobilenetClassification) {
  const std::string graph0_path =
      TestFilePath("mobilenet_quant_v1_224_feature_layers-custom_op.tflite");
  const std::string graph1_path =
      TestFilePath("mobilenet_quant_v1_224_head_layers.tflite");
  const std::string expected_graph =
      TestFilePath("mobilenet_quant_v1_1.0_224_partial_delegation.tflite");
  TestConcatModels(graph0_path, graph1_path, expected_graph);
}

TEST(TfliteGraphUtilTest, ConcatMobilenetSSD) {
  const std::string graph0_path = TestFilePath(
      "mobilenet_ssd_v2_coco_8bit_mini_tensor_feature_layers-custom_op.tflite");
  const std::string graph1_path =
      TestFilePath("mobilenet_ssd_v2_coco_8bit_mini_tensor_head_layers.tflite");
  const std::string expected_graph = TestFilePath(
      "mobilenet_ssd_v2_coco_8bit_mini_tensor_partial_delegation.tflite");
  TestConcatModels(graph0_path, graph1_path, expected_graph);
}

}  // namespace
}  // namespace tools
}  // namespace coral

int main(int argc, char** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  gflags::ParseCommandLineFlags(&argc, &argv, true);
  return RUN_ALL_TESTS();
}
